name: Update Macro Monitor

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Skip outside market hours (PT)
    - name: Gate by market hours (PT)
      id: gate
      run: |
        WITHIN=$(python - <<'PY'
from datetime import datetime, time as dtime
from zoneinfo import ZoneInfo
now = datetime.now(ZoneInfo("America/Los_Angeles"))
is_weekday = now.weekday() < 5
within = is_weekday and (dtime(6,30) <= now.time() <= dtime(13,0))
print(str(within).lower())
PY
)
        echo "within=${WITHIN}" >> $GITHUB_OUTPUT
        echo "Within market hours: ${WITHIN}"

    - name: Generate report
      if: steps.gate.outputs.within == 'true'
      run: |
        python report.py

    - name: Commit and push updates
      if: steps.gate.outputs.within == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add macro_monitor.pdf macro_tracker.xlsx || true
        if ! git diff --cached --quiet; then
          git commit -m "Auto update macro monitor"
          git push
        else
          echo "No changes to commit."
        fi
