name: Update Macro Monitor (Fixed)

on:
  workflow_dispatch:          # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0    # Fetch all history for all branches

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate report
      run: python macro_report_fixed.py

    - name: Commit and push updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Pull latest changes first
        git pull origin main --rebase
        
        # Add the generated files
        git add macro_monitor.pdf macro_tracker.xlsx || true
        
        # Check if there are changes to commit
        if ! git diff --cached --quiet; then
          git commit -m "Auto update macro monitor - $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        else
          echo "No changes to commit."
        fi
