name: Run macro monitor once (manual)

on:
  workflow_dispatch:  # manual run button

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pandas_datareader matplotlib

      - name: Generate macro report (one-shot)
        run: python macro_report_full.py

      - name: Commit and push updated reports
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add macro_monitor_full.pdf global_macro_tracker_full.xlsx || true
          git commit -m "Run-once: update reports" || echo "Nothing to commit"
          git push
